brifui-org/brif-ui

.github/workflows/release.yml
=> ci: updated publish workflows

.changeset/pre.json, package.json
=> chore: release theme plugin

.github/workflows/release.yml
=> ci: updated workflows

.changeset/dull-yaks-refuse.md, docs/stories/Menu.stories.tsx, packages/components/menu/src/context.tsx, packages/components/menu/src/item.tsx, packages/components/menu/src/track.tsx, packages/core/src/utils/pick-children-by-type/pick-children-by-type.ts
=> feat: updated menu active track

docs/app/layout.tsx, docs/components/header.tsx, docs/components/index.ts, docs/components/logo.tsx, docs/components/sidebar.tsx, docs/layouts/index.tsx, packages/components/container/src/container.tsx, packages/components/menu/src/context.tsx, packages/components/menu/src/item.tsx, packages/components/menu/src/track.tsx
=> feat: updated docs

.changeset/rare-crabs-study.md, docs/components/sidebar.tsx, packages/components/menu/src/context.tsx, packages/components/menu/src/item.tsx, packages/components/menu/src/section.tsx
=> feat: updated menu section styles

.changeset/moody-monkeys-check.md, docs/app/(layouts)/box/page.tsx, docs/app/(layouts)/flex/page.tsx, docs/app/(layouts)/grid/page.tsx, docs/app/(layouts)/space/page.tsx, docs/app/(overview)/getting-started/page.tsx, docs/app/(overview)/introduction/page.tsx, docs/app/(overview)/releases/page.tsx, docs/app/not-found.tsx, docs/app/page.tsx, docs/components/sidebar.tsx, docs/layouts/index.tsx, docs/stories/Input.stories.tsx, packages/components/input/src/input.tsx, packages/components/menu/package.json, packages/components/menu/src/context.tsx, packages/components/menu/src/item.tsx, packages/components/menu/src/section.tsx, yarn.lock
=> style: updated input styles

docs/package.json, packages/components/typography/package.json, yarn.lock
=> chore: updated lockfile

.changeset/happy-timers-yawn.md, docs/app/docs/(components)/checkbox/page.tsx, docs/app/docs/(components)/form/page.tsx, docs/app/docs/(components)/input/page.tsx, docs/app/docs/layout.tsx, docs/components/menu.tsx, docs/components/page.tsx, docs/package.json, packages/components/accordion/src/variants.ts, packages/components/button/src/variants.ts, packages/components/entry/src/index.ts, packages/components/form/clean-package.config.json, packages/components/form/eslint.config.mjs, packages/components/form/package.json, packages/components/form/src/context.tsx, packages/components/form/src/form.spec.tsx, packages/components/form/src/form.tsx, packages/components/form/src/index.ts, packages/components/form/src/variants.ts, packages/components/form/tsconfig.json, packages/components/form/vitest.config.ts, packages/components/input/src/variants.ts, yarn.lock
=> feat: added form

.changeset/moody-cats-shout.md, docs/app/docs/(components)/accordion/page.tsx, docs/app/docs/(components)/button/page.tsx, docs/app/docs/(components)/form/page.tsx, docs/app/docs/layout.tsx, docs/app/layout.tsx, docs/app/providers/index.tsx, docs/app/providers/menu-context.tsx, docs/components/header.tsx, docs/components/menu.tsx, docs/components/page.tsx, docs/package.json, packages/components/accordion/src/accordion.tsx, packages/components/accordion/src/variants.ts, packages/components/button/src/button.tsx, packages/components/button/src/variants.ts, packages/components/form/src/form.tsx, packages/components/form/src/variants.ts, yarn.lock
=> feat: updated styles

.changeset/calm-cheetahs-behave.md, .yarnrc.yml, docs/package.json, packages/cli/package.json, packages/components/accordion/package.json, packages/components/button/package.json, packages/components/button/src/button.tsx, packages/components/card/package.json, packages/components/checkbox/package.json, packages/components/entry/package.json, packages/components/form/package.json, packages/components/input/package.json, packages/components/select/package.json, packages/mocks/package.json, packages/postcss/package.json, packages/styled/package.json, packages/theme/package.json, packages/types/package.json, packages/utils/package.json, plop/component/package.json.hbs, yarn.lock
=> feat: updated

.changeset/bright-cherries-jump.md, packages/theme/package.json, yarn.lock
=> chore: updated deps

.changeset/friendly-experts-relate.md, package.json, packages/components/entry/clean-package.config.json, packages/styled/package.json
=> chore: updated typings

.changeset/shy-experts-hammer.md, packages/styled/package.json
=> chore: updated styled package to ESM only

.github/workflows/release.yml, package.json
=> ci: fixed failed ci

.changeset/four-doors-tickle.md, packages/cli/dist/chunk-TVO3LTQB.mjs, packages/cli/dist/commands/codegen.d.mts, packages/cli/dist/commands/codegen.d.ts, packages/cli/dist/index.d.mts, packages/cli/dist/index.d.ts, packages/cli/dist/index.js, packages/cli/dist/index.mjs, packages/cli/dist/main.d.mts, packages/cli/dist/main.d.ts, packages/cli/dist/main.js, packages/cli/dist/main.mjs, packages/theme/postcss.cjs
=> fix: fixed esm import in cjs

.changeset/bright-maps-guess.md, docs/app/docs/(tokens)/typography/page.tsx, packages/cli/dist/chunk-3BTIAQTU.mjs, packages/cli/dist/index.js, packages/cli/dist/index.mjs, packages/cli/dist/main.js, packages/cli/dist/main.mjs, packages/components/button/src/variants.ts, packages/components/checkbox/src/variants.ts, packages/theme/src/colors/sys/background.ts, packages/theme/src/colors/sys/border.ts, packages/theme/src/colors/sys/text.ts, packages/theme/src/sizing/index.ts, plop/component/package.json.hbs, plopfile.js
=> feat: updated theme tokens

.changeset/calm-ligers-grab.md, docs/app/docs/(components)/toast/page.tsx, docs/components/base-layout.tsx, docs/components/menu.tsx, packages/components/entry/src/index.ts, packages/components/input/src/variants.ts, packages/components/toast/clean-package.config.json, packages/components/toast/eslint.config.mjs, packages/components/toast/package.json, packages/components/toast/src/index.ts, packages/components/toast/src/toast.spec.tsx, packages/components/toast/src/toast.tsx, packages/components/toast/src/variants.ts, packages/components/toast/tsconfig.json, packages/components/toast/vitest.config.ts, plop/component/package.json.hbs, plopfile.js, yarn.lock
=> feat: added toast

.changeset/tasty-chefs-wave.md, docs/app/docs/(components)/accordion/page.tsx, docs/app/docs/(components)/accordion/snippet.ts, docs/app/docs/(components)/avatar/page.tsx, docs/app/docs/(components)/avatar/snippet.ts, docs/app/docs/(components)/button/page.tsx, docs/app/docs/(components)/button/snippet.ts, docs/app/docs/(components)/spinner/page.tsx, docs/app/docs/(components)/spinner/snippet.ts, docs/components/menu.tsx, docs/components/page.tsx, docs/package.json, packages/components/entry/src/index.ts, packages/components/spinner/clean-package.config.json, packages/components/spinner/eslint.config.mjs, packages/components/spinner/package.json, packages/components/spinner/src/index.ts, packages/components/spinner/src/spinner.spec.tsx, packages/components/spinner/src/spinner.tsx, packages/components/spinner/src/variants.ts, packages/components/spinner/tsconfig.json, packages/components/spinner/vitest.config.ts, yarn.lock
=> feat: released spinner and added code snippet

.changeset/slimy-pumas-arrive.md, docs/app/docs/(components)/sidebar/page.tsx, docs/app/docs/(components)/sidebar/snippet.ts, docs/app/docs/(components)/tooltip/page.tsx, docs/app/docs/(components)/tooltip/snippet.ts, docs/app/providers/index.tsx, docs/components/menu.tsx, package.json, packages/components/entry/package.json, packages/components/entry/src/index.ts, packages/components/sidebar/src/context.tsx, packages/components/sidebar/src/index.ts, packages/components/sidebar/src/sidebar.tsx, packages/components/sidebar/src/variants.ts, packages/components/tooltip/clean-package.config.json, packages/components/tooltip/eslint.config.mjs, packages/components/tooltip/package.json, packages/components/tooltip/src/index.ts, packages/components/tooltip/src/tooltip.spec.tsx, packages/components/tooltip/src/tooltip.tsx, packages/components/tooltip/src/variants.ts, packages/components/tooltip/tsconfig.json, packages/components/tooltip/vitest.config.ts, plop/component/package.json.hbs, yarn.lock
=> feat: added tooltip

.changeset/silly-colts-hunt.md, docs/app/docs/(tokens)/colors/page.tsx, docs/app/docs/installation/page.tsx, docs/app/docs/introduction/page.tsx, docs/components/header.tsx, docs/components/inline-link.tsx, docs/components/menu.tsx, packages/components/text/src/text.tsx, packages/components/text/src/variants.ts
=> docs: added color tokens

.changeset/nice-swans-move.md, docs/app/docs/installation/page.tsx, docs/app/docs/introduction/page.tsx, docs/components/page.tsx, packages/components/codeblock/src/variants.ts, packages/components/table/src/variants.ts
=> fix: codeblock hover issue

.changeset/new-parrots-allow.md, packages/cli/package.json, packages/mocks/package.json, packages/styled/package.json, packages/theme/package.json, packages/types/package.json, yarn.lock
=> feat: bumped panda to 0.53.1

packages/cli/dist/chunk-AZJR4JIW.mjs, packages/cli/dist/chunk-TJP3HTNZ.mjs, packages/cli/dist/commands/codegen.d.mts, packages/cli/dist/commands/codegen.d.ts, packages/cli/dist/commands/codegen.mjs, packages/cli/dist/index.d.mts, packages/cli/dist/index.d.ts, packages/cli/dist/index.js, packages/cli/dist/index.mjs, packages/cli/dist/main.d.mts, packages/cli/dist/main.d.ts, packages/cli/dist/main.js, packages/cli/dist/main.mjs, packages/cli/dist/utils/logger.d.mts, packages/cli/dist/utils/logger.d.ts, packages/theme/src/configs/define-config/resolve-config.ts, packages/theme/src/presets/index.ts, packages/theme/src/themes/dark.ts, packages/theme/src/themes/index.ts, packages/theme/src/themes/light.ts, packages/theme/src/tokens/index.ts, packages/types/src/colors.ts, packages/types/src/theme.ts
=> feat: fixed theme typings

.changeset/grumpy-camels-attend.md, docs/app/docs/introduction/page.tsx, docs/app/page.tsx, docs/components/header.tsx, package.json, packages/components/badge/clean-package.config.json, packages/components/badge/eslint.config.mjs, packages/components/badge/package.json, packages/components/badge/src/badge.spec.tsx, packages/components/badge/src/badge.tsx, packages/components/badge/src/index.ts, packages/components/badge/src/variants.ts, packages/components/badge/tsconfig.json, packages/components/badge/vitest.config.ts, packages/components/entry/package.json, packages/components/entry/src/index.ts, packages/theme/src/presets/index.ts, yarn.lock
=> feat: added badge

.changeset/witty-steaks-complain.md, docs/app/docs/(tokens)/configuration/page.tsx, docs/brifui.config.ts, docs/components/menu.tsx, docs/components/page.tsx, packages/cli/dist/chunk-XBH26IAH.mjs, packages/cli/dist/chunk-YG3N52Q6.mjs, packages/cli/dist/commands/codegen.d.mts, packages/cli/dist/commands/codegen.d.ts, packages/cli/dist/commands/codegen.mjs, packages/cli/dist/index.d.mts, packages/cli/dist/index.d.ts, packages/cli/dist/index.js, packages/cli/dist/index.mjs, packages/cli/dist/main.d.mts, packages/cli/dist/main.d.ts, packages/cli/dist/main.js, packages/cli/dist/main.mjs, packages/cli/dist/utils/logger.d.mts, packages/cli/dist/utils/logger.d.ts, packages/theme/src/configs/define-config/define-config.ts, packages/theme/src/configs/define-config/resolve-config.ts, packages/theme/src/presets/index.ts, packages/types/src/theme.ts
=> feat: added theme configurations support

packages/styled/package.json, yarn.lock
=> feat: fixed failed install step

.changeset/orange-crabs-sin.md, packages/cli/dist/chunk-F6RHK7GD.js, packages/cli/dist/chunk-FLL623GO.js, packages/cli/dist/commands/codegen.cjs, packages/cli/dist/commands/codegen.js, packages/cli/dist/index.cjs, packages/cli/dist/index.js, packages/cli/dist/main.cjs, packages/cli/dist/main.js, packages/cli/src/commands/codegen.ts, packages/styled/rslib.config.ts
=> fix: improve styled transpile step and update dependencies

.changeset/fluffy-ways-dance.md, docs/app/docs/(components)/checkbox/page.tsx, packages/cli/dist/chunk-CGBAM74O.js, packages/cli/dist/chunk-LUFSVT5Y.js, packages/cli/dist/commands/codegen.js, packages/cli/dist/index.cjs, packages/cli/dist/index.js, packages/cli/dist/main.cjs, packages/cli/dist/main.js, packages/components/checkbox/src/checkbox.tsx, packages/components/checkbox/src/context.tsx, packages/components/checkbox/src/variants.ts, packages/theme/src/presets/index.ts, packages/theme/src/tokens/shadows/index.ts, packages/types/src/shadows.ts
=> feat: updated box shadow utility

.changeset/gorgeous-starfishes-provide.md, docs/app/docs/(components)/dialog/page.tsx, docs/app/docs/(components)/dialog/snippet.ts, docs/components/menu.tsx, packages/components/dialog/clean-package.config.json, packages/components/dialog/eslint.config.mjs, packages/components/dialog/package.json, packages/components/dialog/src/context.tsx, packages/components/dialog/src/dialog.spec.tsx, packages/components/dialog/src/dialog.tsx, packages/components/dialog/src/index.ts, packages/components/dialog/src/variants.ts, packages/components/dialog/tsconfig.json, packages/components/dialog/vitest.config.ts, packages/components/entry/package.json, packages/components/entry/src/index.ts, packages/theme/src/tokens/fonts/letter-spacings.ts, packages/theme/src/tokens/index.ts, packages/theme/src/tokens/sizing/index.ts, packages/types/src/fonts.ts, packages/types/src/sizing.ts, packages/types/src/theme.ts, yarn.lock
=> feat: added dialog

packages/components/dialog/package.json
=> feat: fixed wrong version

packages/components/scrollarea/src/scrollarea.spec.tsx
=> fix: failed scrollarea build step

packages/components/scrollarea/src/context.tsx, packages/components/scrollarea/src/scrollarea.spec.tsx
=> fixed: failed docs build

docs/app/docs/(components)/sidebar/page.tsx, docs/app/providers/index.tsx, packages/components/sidebar/src/context.tsx, packages/components/sidebar/src/sidebar.tsx
=> feat: separated sidebar provider

.changeset/lucky-pumas-sparkle.md, packages/components/sidebar/src/variants.ts
=> feat: fixed sidebar header + footer background issue

.changeset/lucky-pumas-sparkle.md, docs/components/base-layout.tsx, docs/components/menu.tsx, packages/components/sidebar/src/variants.ts
=> docs: updated mobile menu

.changeset/beige-tips-jump.md, docs/components/base-layout.tsx, docs/components/page.tsx, packages/components/button/src/button.tsx, packages/components/button/src/variants.ts
=> fix: fixed flickering transition on hover

.changeset/five-walls-cheer.md, docs/app/docs/(components)/codeblock/page.tsx, docs/app/docs/(components)/form/page.tsx, docs/app/docs/(components)/form/snippet.ts, docs/app/docs/(components)/input/page.tsx, docs/app/docs/(components)/input/snippet.ts, docs/app/docs/(components)/sidebar/page.tsx, docs/components/base-layout.tsx, docs/components/page.tsx, packages/components/codeblock/src/codeblock.tsx, packages/components/codeblock/src/variants.ts
=> feat: improved codeblock styles

docs/app/docs/(components)/card/page.tsx, docs/app/docs/(tokens)/colors/page.tsx, docs/app/docs/installation/page.tsx, docs/app/docs/introduction/page.tsx, docs/components/header.tsx, docs/components/menu.tsx, docs/components/page.tsx
=> feat: updated docs styles

.changeset/tough-brooms-talk.md
=> feat: release codeblock

package.json
=> fix: lower node version

README.md
=> chore: added README.md symlink

docs/app/docs/(components)/dialog/page.tsx, docs/app/docs/installation/page.tsx, docs/components/header.tsx, docs/components/landing-page-layout.tsx, packages/components/codeblock/src/codeblock.tsx, packages/components/dialog/src/context.tsx, packages/components/dialog/src/dialog.tsx, packages/components/form/src/form.tsx, packages/theme/src/presets/index.ts, packages/theme/src/recipes/codeblock.ts, packages/theme/src/recipes/dialog.ts, packages/theme/src/recipes/form.ts, packages/theme/src/recipes/index.ts
=> feat: added dialog + form + codeblock recipes

packages/components/form/src/context.tsx
=> fix: failed install build

docs/app/docs/(components)/accordion/page.tsx, docs/app/docs/(components)/alert/page.tsx, docs/app/docs/(components)/avatar/apis.ts, docs/app/docs/(components)/avatar/page.tsx, docs/app/docs/(components)/button/apis.ts, docs/app/docs/(components)/button/page.tsx, docs/app/docs/(components)/card/apis.ts, docs/app/docs/(components)/card/page.tsx, docs/app/docs/(components)/checkbox/apis.ts, docs/app/docs/(components)/checkbox/page.tsx, docs/app/docs/(components)/codeblock/apis.ts, docs/app/docs/(components)/codeblock/page.tsx, docs/app/docs/(components)/dialog/apis.ts, docs/app/docs/(components)/dialog/page.tsx, docs/app/docs/(components)/form/apis.ts, docs/app/docs/(components)/form/page.tsx, docs/app/docs/(components)/input/apis.ts, docs/app/docs/(components)/input/page.tsx, docs/components/page.tsx, packages/components/accordion/src/accordion.tsx, packages/components/input/src/input.tsx, packages/theme/src/presets/index.ts, packages/theme/src/recipes/accordion.ts, packages/theme/src/recipes/index.ts, packages/theme/src/recipes/input.ts
=> feat: added input recipes

docs/app/docs/(components)/radio-group/apis.ts, docs/app/docs/(components)/radio-group/page.tsx, docs/app/docs/(components)/scrollarea/apis.ts, docs/app/docs/(components)/scrollarea/page.tsx, docs/components/page.tsx, packages/components/radio/src/context.tsx, packages/components/radio/src/radio.tsx, packages/components/scrollarea/src/context.tsx, packages/components/scrollarea/src/scrollarea.tsx, packages/theme/src/presets/index.ts, packages/theme/src/recipes/accordion.ts, packages/theme/src/recipes/index.ts, packages/theme/src/recipes/radio-group.ts, packages/theme/src/recipes/scrollarea.ts
=> feat: added radio-group recipe

docs/app/docs/(components)/select/apis.ts, docs/app/docs/(components)/select/page.tsx, docs/app/docs/(components)/select/snippet.ts, packages/components/select/src/context.tsx, packages/components/select/src/select.tsx, packages/components/table/src/variants.ts, packages/theme/src/presets/index.ts, packages/theme/src/recipes/index.ts, packages/theme/src/recipes/select.ts
=> feat: added select recipe
